### ISSUE TITLE
Issue with negative temperature in centigrade

### ISSUE THREAD

**Issue by Enigmatique** [andreiva/raspberry-pi-bme280#4] opened 2017-01-20 15:33 UTC
Hello,

as soon as we have the negative temperature something is wrong:
_**pi@raspberrypi ~/test/raspberry-pi-bme280 $ ./bme280
{"sensor":"bme280", "humidity":100.00, "pressure":1581.26, "temperature":404.47, "altitude":-3920.22, "timestamp":1484926228}**_

If I use another C++ coded program for BME280 sensor with Raspberry Pi I receive real values:
**pi@raspberrypi ~/test/raspberry-pi-bme280 $ BME280
_**Temperature in Celsius : -5.1 C
Dew point in Celsius : -11.5 C
Pressure : 1018.63 hPa
Pressure rel : 1040.69 hPa
Relative Humidity : 61 RH**_**

It seems that there is some issue with the calculation with the negative values.
Could you please check it ?

With best regards,

**Comment by andreiva** [comment] 2017-01-20 16:53
Sure,  I'll check it.

**Comment by andreiva** [comment] 2017-01-21 14:18
Bug fixed.
The problem was caused by unsigned variables.

**Comment by Enigmatique** [comment] 2017-01-21 20:18
Thanks a lot. I confirm that bug has been fixed. Finally, it is working properly. If you agree I will close it.

**_pi@raspberrypi ~/test/raspberry-pi-bme280 $ ./bme280 
{"sensor":"bme280", "humidity":66.99, "pressure":1017.14, "temperature":-6.24, "altitude":-34.45, "timestamp":1485029659}_**
And other C++ program with the BME280:
**_pi@raspberrypi ~/test/raspberry-pi-bme280 $ BME280 
Temperature in Celsius : -6.2 C 
Dew point in Celsius : -11.4 C 
Pressure : 1017.13 hPa 
Pressure rel : 1039.24 hPa
Relative Humidity : 67 RH_**

**Comment by andreiva** [comment] 2017-01-21 21:46
Looks fine to me. You may close the issue.

**Closed as completed** 2017-01-22 05:25 UTC
